basePath: /
definitions:
  models.AuthForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/models.ErrorResponseDetail'
    type: object
  models.ErrorResponseDetail:
    properties:
      code:
        type: string
      details:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  models.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Example of working Backend created during class
  title: FGO23 GIN API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: login information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.AuthForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Login Student
  /auth/new:
    post:
      consumes:
      - application/json
      parameters:
      - description: register information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.AuthForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Register Student
  /ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Example of Ping then Get Students
swagger: "2.0"
